spring:
  application:
    name: service-order

  profiles:
    active: prod
    include:
      - feign
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        import-check:
          enabled: false

server:
  port: 9000
