spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                  allowed-origins:
                    - '*'
                  allowed-methods:
                    - 'GET'
          routes:
            - id: order-route
              uri: lb://service-order
              predicates:
                - Path=/api/order/**
              filters:
                - RewritePath=/api/(?<segment>.*), /${segment}
              order: 1

            - id: product-route
              uri: lb://service-product
              predicates:
                - Path=/api/product/**

            - id: bing-route
              uri: https://www.bing.com
              predicates:
                - Path=/api/order/**
              filters:
                - RewritePath=/api/order/(?<segment>.*), /${segment}
                - AddRequestHeader=Access-Control-Allow-Origin,'/**'
                - AddRequestParameter=q,"BLG vs T1"
              order: 0
            - id: baidu-route
              uri: https://chat.deepseek.com/a/chat/s
              predicates:
                - Path=/api/order/**
              filters:
                - RewritePath=/api/order/(?<segment>.*), /${segment}
                - ModifyRequestBody=